#!/bin/sh

if [ ! -e main ] ; then
    echo Executable file "main" not available. Building...
    make main
fi

TESTS=tests/*.test

for TEST in ${TESTS} ; do
    echo Running test ${TEST}

    OUT_FILE=$(mktemp)
    ./main $TEST | tee ${OUT_FILE}
    echo
    diff -w tests/$(basename "${TEST}" .test).out "${OUT_FILE}"

    RES=$?
    if [ $RES != 0 ] ; then
        break
    fi
    echo
    echo
done
